FROM grafana/grafana:9.0.0

ENV GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
ENV GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}

COPY ./config/grafana.ini /etc/grafana/grafana.ini
COPY ./config/provisioning /etc/grafana/provisioning
COPY ./dashboards /etc/grafana/dashboards