global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'LitellmOpenAi'
    static_configs:
      - targets: ['LitellmOpenAi:4000']
    metrics_path: '/metrics'