model_list:
  - model_name: os.environ/MODEL_NAME
    litellm_params:
      model: azure/AZURE_DEPLOYMENT_NAME
      api_base: os.environ/AZURE_ENDPOINT
      api_key: os.environ/OPEN_AI_API_KEY
      api_version: os.environ/AZURE_API_VERSION

  - model_name: os.environ/GPT_MINI_NAME
    litellm_params:
      model: azure/GPT_MINI_DEPLOYMENT_NAME
      api_base: os.environ/GPT_MINI_ENDPOINT
      api_key: os.environ/GPT_MINI_APIKEY
      api_version: os.environ/GPT_MINI_API_VERSION

  - model_name: os.environ/EMBEDDINGS_MODEL_NAME
    litellm_params:
      model: azure/EMBEDDINGS_MODEL_DEPLOYMENT_NAME
      api_base: os.environ/EMBEDDINGS_MODEL_ENDPOINT
      api_key: os.environ/EMBEDDINGS_MODEL_APIKEY
      api_version: os.environ/EMBEDDINGS_MODEL_VERSION

litellm_settings:
  callbacks: ["prometheus"]